### ISSUE TITLE
Lepsza obsługa stałych konfiguracji przez wprowadzenie properties

### ISSUE THREAD

**Issue by liscju** [liscju/DockerManager#9]
W kodzie nie powinny sie pojawiać stałe typu nr ip serwera do którego się łączy,powinny takie stałe być wydzielone do pliku properties.

**Comment by liscju** [comment]
Zrobione, jest nawet pierwsza stała !

**Comment by latacz** [comment]
Robota trochę bez sensu, docelowo tam będzie można wybrać adres serwera....

**Comment by liscju** [comment]
Zgadzam sie, ale ze prawie wszystkie issue/commity/funkcjonalnosci w tym projekcie maja wlasnie taki sens- "wrzucam cos bo moze sie przyda" - to wrzucilem.
